# Run a development environment
---
networks:
  private-net:

volumes:
  redis-cache:
    driver: local

services:
  # --- REDIS ---
  redis:
    image: redis/redis-stack:latest
    networks:
      - private-net
    ports:
      - "6379:6379/tcp"
    environment:
      REDIS_ARGS: --requirepass ${REDIS_PASSWORD:?Missing Redis Password} --protected-mode yes
    volumes:
      - redis-cache:/data

  # --- BACKEND API ---
  api:
    image: ghcr.io/decksettings/deck-verified-api:latest
    build:
      context: .
      dockerfile: ./packages/backend/docker/Dockerfile
    user: "1000:1000"
    #command: npm run watch:backend
    #command: npm run serve-no-tasks
    command: npm run serve
    ports:
      - "9022:9022"
    depends_on:
      - redis
    networks:
      - private-net
    environment:
      RUN_SCHEDULED_TASKS_ON_START: ${RUN_SCHEDULED_TASKS_ON_START:-false}
      # -- GitHub token (required to increase rate limits on API calls).
      GH_TOKEN: ${GH_TOKEN:?}
      # -- Cache Config
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:?Missing Redis Password}
    healthcheck:
      test: ["CMD", "wget", "--header=User-Agent: Compose-HealthChecker/1.0", "--spider", "--no-verbose", "--tries=1", "--timeout=3", "http://localhost:9022/deck-verified/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    #volumes:
    # NOTE: Ensure you run 'npm install' first due to the ./backend volume mounted into the container.
    #  - ./:/app/

  # --- FRONTEND ---
  web-ssr:
    image: ghcr.io/decksettings/deck-verified-web-ssr:latest
    build:
      context: .
      dockerfile: ./packages/frontend/docker/ssr.Dockerfile
    depends_on:
      - api
    networks:
      - private-net
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--header=User-Agent: Compose-HealthChecker/1.0", "--spider", "--no-verbose", "--tries=1", "--timeout=3", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      # Used by SSR to call the API directly instead of hitting the SSR server
      SSR_API_ORIGIN: http://api:9022

  # --- FRONTEND ---
  web:
    image: ghcr.io/decksettings/deck-verified-web:latest
    build:
      context: .
      dockerfile: ./packages/frontend/docker/Dockerfile
    ports:
      - "9021:9021"
    depends_on:
      - api
      - web-ssr
    networks:
      - private-net
    healthcheck:
      test: ["CMD", "wget", "--header=User-Agent: Compose-HealthChecker/1.0", "--spider", "--no-verbose", "--tries=1", "--timeout=3", "http://localhost:9021/deck-verified/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    #volumes:
    # NOTE: Ensure you run 'npm install && npm run build' first due to the ./dist/spa volume mounted into the container.
    #  - ./dist/spa:/usr/share/nginx/html/deck-verified
