export interface SelectOption {
  label: string;
  value: string;
}

export const COUNTRY_OPTIONS: SelectOption[] = [
  { label: 'Afghanistan', value: 'AF' },
  { label: 'Åland Islands', value: 'AX' },
  { label: 'Albania', value: 'AL' },
  { label: 'Algeria', value: 'DZ' },
  { label: 'American Samoa', value: 'AS' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Anguilla', value: 'AI' },
  { label: 'Antarctica', value: 'AQ' },
  { label: 'Antigua and Barbuda', value: 'AG' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Aruba', value: 'AW' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Azerbaijan', value: 'AZ' },
  { label: 'Bahamas', value: 'BS' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbados', value: 'BB' },
  { label: 'Belarus', value: 'BY' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Belize', value: 'BZ' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Bermuda', value: 'BM' },
  { label: 'Bhutan', value: 'BT' },
  { label: 'Bolivia (Plurinational State of)', value: 'BO' },
  { label: 'Bonaire, Sint Eustatius and Saba', value: 'BQ' },
  { label: 'Bosnia and Herzegovina', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Bouvet Island', value: 'BV' },
  { label: 'Brazil', value: 'BR' },
  { label: 'British Indian Ocean Territory', value: 'IO' },
  { label: 'Brunei Darussalam', value: 'BN' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Burkina Faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Cabo Verde', value: 'CV' },
  { label: 'Cambodia', value: 'KH' },
  { label: 'Cameroon', value: 'CM' },
  { label: 'Canada', value: 'CA' },
  { label: 'Cayman Islands', value: 'KY' },
  { label: 'Central African Republic', value: 'CF' },
  { label: 'Chad', value: 'TD' },
  { label: 'Chile', value: 'CL' },
  { label: 'China', value: 'CN' },
  { label: 'Christmas Island', value: 'CX' },
  { label: 'Cocos (Keeling) Islands', value: 'CC' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Comoros', value: 'KM' },
  { label: 'Congo (Democratic Republic of the)', value: 'CD' },
  { label: 'Congo', value: 'CG' },
  { label: 'Cook Islands', value: 'CK' },
  { label: 'Costa Rica', value: 'CR' },
  { label: 'Côte d\'Ivoire', value: 'CI' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Curaçao', value: 'CW' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czechia', value: 'CZ' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Djibouti', value: 'DJ' },
  { label: 'Dominica', value: 'DM' },
  { label: 'Dominican Republic', value: 'DO' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Egypt', value: 'EG' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Equatorial Guinea', value: 'GQ' },
  { label: 'Eritrea', value: 'ER' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Eswatini', value: 'SZ' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Falkland Islands (Malvinas)', value: 'FK' },
  { label: 'Faroe Islands', value: 'FO' },
  { label: 'Fiji', value: 'FJ' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'French Guiana', value: 'GF' },
  { label: 'French Polynesia', value: 'PF' },
  { label: 'French Southern Territories', value: 'TF' },
  { label: 'Gabon', value: 'GA' },
  { label: 'Gambia', value: 'GM' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Germany', value: 'DE' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Gibraltar', value: 'GI' },
  { label: 'Greece', value: 'GR' },
  { label: 'Greenland', value: 'GL' },
  { label: 'Grenada', value: 'GD' },
  { label: 'Guadeloupe', value: 'GP' },
  { label: 'Guam', value: 'GU' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guernsey', value: 'GG' },
  { label: 'Guinea-Bissau', value: 'GW' },
  { label: 'Guinea', value: 'GN' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Haiti', value: 'HT' },
  { label: 'Heard Island and McDonald Islands', value: 'HM' },
  { label: 'Holy See', value: 'VA' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hong Kong', value: 'HK' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Iceland', value: 'IS' },
  { label: 'India', value: 'IN' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Iran (Islamic Republic of)', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Isle of Man', value: 'IM' },
  { label: 'Israel', value: 'IL' },
  { label: 'Italy', value: 'IT' },
  { label: 'Jamaica', value: 'JM' },
  { label: 'Japan', value: 'JP' },
  { label: 'Jersey', value: 'JE' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Kiribati', value: 'KI' },
  { label: 'Korea (Democratic People\'s Republic of)', value: 'KP' },
  { label: 'Korea (Republic of)', value: 'KR' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Kyrgyzstan', value: 'KG' },
  { label: 'Lao People\'s Democratic Republic', value: 'LA' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Lebanon', value: 'LB' },
  { label: 'Lesotho', value: 'LS' },
  { label: 'Liberia', value: 'LR' },
  { label: 'Libya', value: 'LY' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Macao', value: 'MO' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'Malawi', value: 'MW' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Maldives', value: 'MV' },
  { label: 'Mali', value: 'ML' },
  { label: 'Malta', value: 'MT' },
  { label: 'Marshall Islands', value: 'MH' },
  { label: 'Martinique', value: 'MQ' },
  { label: 'Mauritania', value: 'MR' },
  { label: 'Mauritius', value: 'MU' },
  { label: 'Mayotte', value: 'YT' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Micronesia (Federated States of)', value: 'FM' },
  { label: 'Moldova (Republic of)', value: 'MD' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Mongolia', value: 'MN' },
  { label: 'Montenegro', value: 'ME' },
  { label: 'Montserrat', value: 'MS' },
  { label: 'Morocco', value: 'MA' },
  { label: 'Mozambique', value: 'MZ' },
  { label: 'Myanmar', value: 'MM' },
  { label: 'Namibia', value: 'NA' },
  { label: 'Nauru', value: 'NR' },
  { label: 'Nepal', value: 'NP' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'New Caledonia', value: 'NC' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Nicaragua', value: 'NI' },
  { label: 'Niger', value: 'NE' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'Niue', value: 'NU' },
  { label: 'Norfolk Island', value: 'NF' },
  { label: 'North Macedonia', value: 'MK' },
  { label: 'Northern Mariana Islands', value: 'MP' },
  { label: 'Norway', value: 'NO' },
  { label: 'Oman', value: 'OM' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Palau', value: 'PW' },
  { label: 'Panama', value: 'PA' },
  { label: 'Papua New Guinea', value: 'PG' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Peru', value: 'PE' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Pitcairn', value: 'PN' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Puerto Rico', value: 'PR' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Réunion', value: 'RE' },
  { label: 'Romania', value: 'RO' },
  { label: 'Russian Federation', value: 'RU' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Saint Barthélemy', value: 'BL' },
  { label: 'Saint Helena, Ascension and Tristan da Cunha', value: 'SH' },
  { label: 'Saint Kitts and Nevis', value: 'KN' },
  { label: 'Saint Lucia', value: 'LC' },
  { label: 'Saint Martin (French part)', value: 'MF' },
  { label: 'Saint Pierre and Miquelon', value: 'PM' },
  { label: 'San Marino', value: 'SM' },
  { label: 'Sao Tome and Principe', value: 'ST' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Senegal', value: 'SN' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Seychelles', value: 'SC' },
  { label: 'Sierra Leone', value: 'SL' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Sint Maarten (Dutch part)', value: 'SX' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Solomon Islands', value: 'SB' },
  { label: 'Somalia', value: 'SO' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'South Georgia and the South Sandwich Islands', value: 'GS' },
  { label: 'South Sudan', value: 'SS' },
  { label: 'Spain', value: 'ES' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'Sudan', value: 'SD' },
  { label: 'Suriname', value: 'SR' },
  { label: 'Svalbard and Jan Mayen', value: 'SJ' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Syrian Arab Republic', value: 'SY' },
  { label: 'Taiwan', value: 'TW' },
  { label: 'Tajikistan', value: 'TJ' },
  { label: 'Tanzania, United Republic of', value: 'TZ' },
  { label: 'Thailand', value: 'TH' },
  { label: 'Timor-Leste', value: 'TL' },
  { label: 'Togo', value: 'TG' },
  { label: 'Tokelau', value: 'TK' },
  { label: 'Tonga', value: 'TO' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Turkmenistan', value: 'TM' },
  { label: 'Turks and Caicos Islands', value: 'TC' },
  { label: 'Tuvalu', value: 'TV' },
  { label: 'Uganda', value: 'UG' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'United Arab Emirates', value: 'AE' },
  { label: 'United Kingdom of Great Britain and Northern Ireland', value: 'GB' },
  { label: 'United States Minor Outlying Islands', value: 'UM' },
  { label: 'United States of America', value: 'US' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Vanuatu', value: 'VU' },
  { label: 'Venezuela (Bolivarian Republic of)', value: 'VE' },
  { label: 'Viet Nam', value: 'VN' },
  { label: 'Virgin Islands (British)', value: 'VG' },
  { label: 'Virgin Islands (U.S.)', value: 'VI' },
  { label: 'Wallis and Futuna', value: 'WF' },
  { label: 'Western Sahara', value: 'EH' },
  { label: 'Yemen', value: 'YE' },
  { label: 'Zambia', value: 'ZM' },
  { label: 'Zimbabwe', value: 'ZW' },
]

export const CURRENCY_OPTIONS: SelectOption[] = [
  { label: 'Afghan Afghani (AFN)', value: 'AFN' },
  { label: 'Albanian Lek (ALL)', value: 'ALL' },
  { label: 'Algerian Dinar (DZD)', value: 'DZD' },
  { label: 'Angolan Kwanza (AOA)', value: 'AOA' },
  { label: 'Argentine Peso (ARS)', value: 'ARS' },
  { label: 'Armenian Dram (AMD)', value: 'AMD' },
  { label: 'Aruban Florin (AWG)', value: 'AWG' },
  { label: 'Australian Dollar (AUD)', value: 'AUD' },
  { label: 'Azerbaijani Manat (AZN)', value: 'AZN' },
  { label: 'Bahamian Dollar (BSD)', value: 'BSD' },
  { label: 'Bahraini Dinar (BHD)', value: 'BHD' },
  { label: 'Bangladeshi Taka (BDT)', value: 'BDT' },
  { label: 'Barbados Dollar (BBD)', value: 'BBD' },
  { label: 'Belarussian Ruble (BYN)', value: 'BYN' },
  { label: 'Belize Dollar (BZD)', value: 'BZD' },
  { label: 'Bermudian Dollar (BMD)', value: 'BMD' },
  { label: 'Bhutanese Ngultrum (BTN)', value: 'BTN' },
  { label: 'Boliviano (BOB)', value: 'BOB' },
  { label: 'Bosnia and Herzegovina Convertible Mark (BAM)', value: 'BAM' },
  { label: 'Botswana Pula (BWP)', value: 'BWP' },
  { label: 'Brazilian Real (BRL)', value: 'BRL' },
  { label: 'Brunei Dollar (BND)', value: 'BND' },
  { label: 'Bulgarian Lev (BGN)', value: 'BGN' },
  { label: 'Burundian Franc (BIF)', value: 'BIF' },
  { label: 'Cambodian Riel (KHR)', value: 'KHR' },
  { label: 'Canadian Dollar (CAD)', value: 'CAD' },
  { label: 'Cape Verde Escudo (CVE)', value: 'CVE' },
  { label: 'Cayman Islands Dollar (KYD)', value: 'KYD' },
  { label: 'CFA Franc BCEAO (XOF)', value: 'XOF' },
  { label: 'CFA Franc BEAC (XAF)', value: 'XAF' },
  { label: 'CFP Franc (XPF)', value: 'XPF' },
  { label: 'Chilean Peso (CLP)', value: 'CLP' },
  { label: 'Chinese Yuan (CNY)', value: 'CNY' },
  { label: 'Colombian Peso (COP)', value: 'COP' },
  { label: 'Comoro Franc (KMF)', value: 'KMF' },
  { label: 'Congolese Franc (CDF)', value: 'CDF' },
  { label: 'Costa Rican Colon (CRC)', value: 'CRC' },
  { label: 'Cuban Convertible Peso (CUC)', value: 'CUC' },
  { label: 'Cuban Peso (CUP)', value: 'CUP' },
  { label: 'Czech Koruna (CZK)', value: 'CZK' },
  { label: 'Danish Krone (DKK)', value: 'DKK' },
  { label: 'Djiboutian Franc (DJF)', value: 'DJF' },
  { label: 'Dominican Peso (DOP)', value: 'DOP' },
  { label: 'East Caribbean Dollar (XCD)', value: 'XCD' },
  { label: 'Egyptian Pound (EGP)', value: 'EGP' },
  { label: 'Eritrean Nakfa (ERN)', value: 'ERN' },
  { label: 'Ethiopian Birr (ETB)', value: 'ETB' },
  { label: 'Euro (EUR)', value: 'EUR' },
  { label: 'Falkland Islands Pound (FKP)', value: 'FKP' },
  { label: 'Fiji Dollar (FJD)', value: 'FJD' },
  { label: 'Gambian Dalasi (GMD)', value: 'GMD' },
  { label: 'Georgian Lari (GEL)', value: 'GEL' },
  { label: 'Ghanaian Cedi (GHS)', value: 'GHS' },
  { label: 'Gibraltar Pound (GIP)', value: 'GIP' },
  { label: 'Guatemalan Quetzal (GTQ)', value: 'GTQ' },
  { label: 'Guinean Franc (GNF)', value: 'GNF' },
  { label: 'Guyanese Dollar (GYD)', value: 'GYD' },
  { label: 'Haitian Gourde (HTG)', value: 'HTG' },
  { label: 'Honduran Lempira (HNL)', value: 'HNL' },
  { label: 'Hong Kong Dollar (HKD)', value: 'HKD' },
  { label: 'Hungarian Forint (HUF)', value: 'HUF' },
  { label: 'Icelandic Króna (ISK)', value: 'ISK' },
  { label: 'Indian Rupee (INR)', value: 'INR' },
  { label: 'Indonesian Rupiah (IDR)', value: 'IDR' },
  { label: 'Iranian Rial (IRR)', value: 'IRR' },
  { label: 'Iraqi Dinar (IQD)', value: 'IQD' },
  { label: 'Israeli New Sheqel (ILS)', value: 'ILS' },
  { label: 'Jamaican Dollar (JMD)', value: 'JMD' },
  { label: 'Japanese Yen (JPY)', value: 'JPY' },
  { label: 'Jordanian Dinar (JOD)', value: 'JOD' },
  { label: 'Kazakhstani Tenge (KZT)', value: 'KZT' },
  { label: 'Kenyan Shilling (KES)', value: 'KES' },
  { label: 'Kuna (HRK)', value: 'HRK' },
  { label: 'Kuwaiti Dinar (KWD)', value: 'KWD' },
  { label: 'Kyrgyzstani Som (KGS)', value: 'KGS' },
  { label: 'Lao Kip (LAK)', value: 'LAK' },
  { label: 'Latvian Lats (LVL)', value: 'LVL' },
  { label: 'Lebanese Pound (LBP)', value: 'LBP' },
  { label: 'Lesotho Loti (LSL)', value: 'LSL' },
  { label: 'Liberian Dollar (LRD)', value: 'LRD' },
  { label: 'Libyan Dinar (LYD)', value: 'LYD' },
  { label: 'Macanese Pataca (MOP)', value: 'MOP' },
  { label: 'Macedonian Denar (MKD)', value: 'MKD' },
  { label: 'Malagasy Ariary (MGA)', value: 'MGA' },
  { label: 'Malawian Kwacha (MWK)', value: 'MWK' },
  { label: 'Malaysian Ringgit (MYR)', value: 'MYR' },
  { label: 'Maldivian Rufiyaa (MVR)', value: 'MVR' },
  { label: 'Mauritanian Ouguiya (MRU)', value: 'MRU' },
  { label: 'Mauritian Rupee (MUR)', value: 'MUR' },
  { label: 'Mexican Peso (MXN)', value: 'MXN' },
  { label: 'Moldovan Leu (MDL)', value: 'MDL' },
  { label: 'Mongolian Tugrik (MNT)', value: 'MNT' },
  { label: 'Moroccan Dirham (MAD)', value: 'MAD' },
  { label: 'Mozambican Metical (MZN)', value: 'MZN' },
  { label: 'Myanmar Kyat (MMK)', value: 'MMK' },
  { label: 'Namibian Dollar (NAD)', value: 'NAD' },
  { label: 'Nepalese Rupee (NPR)', value: 'NPR' },
  { label: 'Netherlands Antillean Guilder (ANG)', value: 'ANG' },
  { label: 'New Taiwan Dollar (TWD)', value: 'TWD' },
  { label: 'New Zealand Dollar (NZD)', value: 'NZD' },
  { label: 'Nicaraguan Córdoba (NIO)', value: 'NIO' },
  { label: 'Nigerian Naira (NGN)', value: 'NGN' },
  { label: 'North Korean Won (KPW)', value: 'KPW' },
  { label: 'Norwegian Krone (NOK)', value: 'NOK' },
  { label: 'Omani Rial (OMR)', value: 'OMR' },
  { label: 'Pakistani Rupee (PKR)', value: 'PKR' },
  { label: 'Panamanian Balboa (PAB)', value: 'PAB' },
  { label: 'Papua New Guinean Kina (PGK)', value: 'PGK' },
  { label: 'Paraguayan Guarani (PYG)', value: 'PYG' },
  { label: 'Peruvian Nuevo Sol (PEN)', value: 'PEN' },
  { label: 'Philippine Peso (PHP)', value: 'PHP' },
  { label: 'Polish Zloty (PLN)', value: 'PLN' },
  { label: 'Pound Sterling (GBP)', value: 'GBP' },
  { label: 'Qatari Rial (QAR)', value: 'QAR' },
  { label: 'Romanian Leu (RON)', value: 'RON' },
  { label: 'Russian Ruble (RUB)', value: 'RUB' },
  { label: 'Rwandan Franc (RWF)', value: 'RWF' },
  { label: 'Saint Helena Pound (SHP)', value: 'SHP' },
  { label: 'Samoan Tala (WST)', value: 'WST' },
  { label: 'São Tomé and Principe Dobra (STN)', value: 'STN' },
  { label: 'Saudi Riyal (SAR)', value: 'SAR' },
  { label: 'Serbian Dinar (RSD)', value: 'RSD' },
  { label: 'Seychelles Rupee (SCR)', value: 'SCR' },
  { label: 'Sierra Leonean Leone (SLL)', value: 'SLL' },
  { label: 'Singapore Dollar (SGD)', value: 'SGD' },
  { label: 'Solomon Islands Dollar (SBD)', value: 'SBD' },
  { label: 'Somali Shilling (SOS)', value: 'SOS' },
  { label: 'South African Rand (ZAR)', value: 'ZAR' },
  { label: 'South Korean Won (KRW)', value: 'KRW' },
  { label: 'South Sudanese Pound (SSP)', value: 'SSP' },
  { label: 'Sri Lankan Rupee (LKR)', value: 'LKR' },
  { label: 'Sudanese Pound (SDG)', value: 'SDG' },
  { label: 'Surinamese Dollar (SRD)', value: 'SRD' },
  { label: 'Swazi Lilangeni (SZL)', value: 'SZL' },
  { label: 'Swedish Krona (SEK)', value: 'SEK' },
  { label: 'Swiss Franc (CHF)', value: 'CHF' },
  { label: 'Syrian Pound (SYP)', value: 'SYP' },
  { label: 'Tajikistani Somoni (TJS)', value: 'TJS' },
  { label: 'Tanzanian Shilling (TZS)', value: 'TZS' },
  { label: 'Thai Baht (THB)', value: 'THB' },
  { label: 'Tongan Paʻanga (TOP)', value: 'TOP' },
  { label: 'Trinidad and Tobago Dollar (TTD)', value: 'TTD' },
  { label: 'Tunisian Dinar (TND)', value: 'TND' },
  { label: 'Turkish Lira (TRY)', value: 'TRY' },
  { label: 'Turkmenistani Manat (TMT)', value: 'TMT' },
  { label: 'UAE Dirham (AED)', value: 'AED' },
  { label: 'Ugandan Shilling (UGX)', value: 'UGX' },
  { label: 'Ukrainian Hryvnia (UAH)', value: 'UAH' },
  { label: 'Uruguayan Peso (UYU)', value: 'UYU' },
  { label: 'US Dollar (USD)', value: 'USD' },
  { label: 'Uzbekistan Som (UZS)', value: 'UZS' },
  { label: 'Vanuatu Vatu (VUV)', value: 'VUV' },
  { label: 'Venezuelan Bolívar (VES)', value: 'VES' },
  { label: 'Vietnamese Dong (VND)', value: 'VND' },
  { label: 'Yemeni Rial (YER)', value: 'YER' },
  { label: 'Zambian Kwacha (ZMW)', value: 'ZMW' },
]

export const currencyCodeToOption = (code?: string): SelectOption | undefined =>
  CURRENCY_OPTIONS.find((c) => c.value.toUpperCase() === String(code || '').toUpperCase())

export const countryCodeToOption = (code?: string): SelectOption | undefined =>
  COUNTRY_OPTIONS.find((c) => c.value.toUpperCase() === String(code || '').toUpperCase())
