name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ 'feature-**', 'fix-**', staging, master ]
  schedule:
    # At 02:30 on Saturday
    - cron: '30 2 * * 6'

jobs:
  build-api-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

      - name: Set Docker image name
        id: set-image
        run: |
          echo  "GITHUB_REF:${GITHUB_REF}"
          echo  "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          VERSION_TAG=${GITHUB_REF#refs/*/}
          SHA_SHORT="${GITHUB_SHA::7}"
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          echo "sha_short=${SHA_SHORT:?}" >> $GITHUB_OUTPUT
          echo "docker_image=ghcr.io/${ORG:?}/deck-verified-api" >> $GITHUB_OUTPUT
          if [[ ${VERSION_TAG%/merge} == 'master' ]]; then
            echo "docker_tag=latest" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} == 'staging' ]]; then
            echo "docker_tag=staging" >> $GITHUB_OUTPUT
          fi

      - name: Log into registry ${{ vars.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Container metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
        with:
          images: ${{ steps.set-image.outputs.docker_image }}
          labels: |
            maintainer=Josh.5
            source.version=${{ steps.set-image.outputs.sha_short }}
            source.project=deck-verified-site
            source.service=deck-verified-api
            org.opencontainers.image.title=deck-verified-api

      - name: Build and push Container image
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          platforms: linux/amd64
          context: .
          file: packages/backend/docker/Dockerfile
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.set-image.outputs.docker_image }}:${{ steps.set-image.outputs.docker_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=deck-verified-api
          cache-to: type=gha,mode=max,scope=deck-verified-api

  build-web-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

      - name: Set Docker image name
        id: set-image
        run: |
          echo  "GITHUB_REF:${GITHUB_REF}"
          echo  "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          VERSION_TAG=${GITHUB_REF#refs/*/}
          SHA_SHORT="${GITHUB_SHA::7}"
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          echo "sha_short=${SHA_SHORT:?}" >> $GITHUB_OUTPUT
          echo "docker_image=ghcr.io/${ORG:?}/deck-verified-web" >> $GITHUB_OUTPUT
          if [[ ${VERSION_TAG%/merge} == 'master' ]]; then
            echo "docker_tag=latest" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} == 'staging' ]]; then
            echo "docker_tag=staging" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} =~ "feature-"* ]]; then
            echo "docker_tag=${VERSION_TAG%/merge}" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} =~ "fix-"* ]]; then
            echo "docker_tag=${VERSION_TAG%/merge}" >> $GITHUB_OUTPUT
          fi

      - name: Log into registry ${{ vars.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Container metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
        with:
          images: ${{ steps.set-image.outputs.docker_image }}
          labels: |
            maintainer=Josh.5
            source.version=${{ steps.set-image.outputs.sha_short }}
            source.project=deck-verified-site
            source.service=deck-verified-web
            org.opencontainers.image.title=deck-verified-web

      - name: Build and push Container image
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          platforms: linux/amd64
          context: .
          file: packages/frontend/docker/Dockerfile
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.set-image.outputs.docker_image }}:${{ steps.set-image.outputs.docker_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=deck-verified-web
          cache-to: type=gha,mode=max,scope=deck-verified-web

  build-web-ssr-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

      - name: Set Docker image name
        id: set-image
        run: |
          echo  "GITHUB_REF:${GITHUB_REF}"
          echo  "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          VERSION_TAG=${GITHUB_REF#refs/*/}
          SHA_SHORT="${GITHUB_SHA::7}"
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          echo "sha_short=${SHA_SHORT:?}" >> $GITHUB_OUTPUT
          echo "docker_image=ghcr.io/${ORG:?}/deck-verified-web-ssr" >> $GITHUB_OUTPUT
          if [[ ${VERSION_TAG%/merge} == 'master' ]]; then
            echo "docker_tag=latest" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} == 'staging' ]]; then
            echo "docker_tag=staging" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} =~ "feature-"* ]]; then
            echo "docker_tag=${VERSION_TAG%/merge}" >> $GITHUB_OUTPUT
          elif [[ ${VERSION_TAG%/merge} =~ "fix-"* ]]; then
            echo "docker_tag=${VERSION_TAG%/merge}" >> $GITHUB_OUTPUT
          fi

      - name: Log into registry ${{ vars.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Container metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
        with:
          images: ${{ steps.set-image.outputs.docker_image }}
          labels: |
            maintainer=Josh.5
            source.version=${{ steps.set-image.outputs.sha_short }}
            source.project=deck-verified-site
            source.service=deck-verified-web-ssr
            org.opencontainers.image.title=deck-verified-web-ssr

      - name: Build and push Container image
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          platforms: linux/amd64
          context: .
          file: packages/frontend/docker/ssr.Dockerfile
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.set-image.outputs.docker_image }}:${{ steps.set-image.outputs.docker_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=deck-verified-web-ssr
          cache-to: type=gha,mode=max,scope=deck-verified-web-ssr

  build-swarm-stack-templates:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build-api-image, build-web-image, build-web-ssr-image]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Swarm Template
        uses: Josh5/action.publish-swarm-stack@841e62adec930611e3c27924982eb85979a42f9c
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          templates_path: infra/swarm
          branch_name: release/latest
